"""Custom Textual themes for mimirlink."""
from textual.theme import Theme

THEMES: dict[str, Theme] = {
    "dracula": Theme(
        name="dracula",
        primary="#bd93f9",
        secondary="#ff79c6",
        accent="#50fa7b",
        warning="#ffb86c",
        error="#ff5555",
        success="#50fa7b",
        foreground="#f8f8f2",
        background="#282a36",
        surface="#44475a",
        panel="#383a59",
        dark=True,
    ),
    "nord": Theme(
        name="nord",
        primary="#88c0d0",
        secondary="#81a1c1",
        accent="#a3be8c",
        warning="#ebcb8b",
        error="#bf616a",
        success="#a3be8c",
        foreground="#eceff4",
        background="#2e3440",
        surface="#3b4252",
        panel="#434c5e",
        dark=True,
    ),
    "tokyo-night": Theme(
        name="tokyo-night",
        primary="#7aa2f7",
        secondary="#bb9af7",
        accent="#73daca",
        warning="#e0af68",
        error="#f7768e",
        success="#9ece6a",
        foreground="#c0caf5",
        background="#1a1b26",
        surface="#24283b",
        panel="#2f3549",
        dark=True,
    ),
    "gruvbox": Theme(
        name="gruvbox",
        primary="#fabd2f",
        secondary="#fe8019",
        accent="#b8bb26",
        warning="#fe8019",
        error="#fb4934",
        success="#b8bb26",
        foreground="#ebdbb2",
        background="#282828",
        surface="#3c3836",
        panel="#504945",
        dark=True,
    ),
    "catppuccin": Theme(
        name="catppuccin",
        primary="#cba6f7",
        secondary="#f38ba8",
        accent="#a6e3a1",
        warning="#fab387",
        error="#f38ba8",
        success="#a6e3a1",
        foreground="#cdd6f4",
        background="#1e1e2e",
        surface="#313244",
        panel="#45475a",
        dark=True,
    ),
    "solarized": Theme(
        name="solarized",
        primary="#268bd2",
        secondary="#2aa198",
        accent="#859900",
        warning="#b58900",
        error="#dc322f",
        success="#859900",
        foreground="#839496",
        background="#002b36",
        surface="#073642",
        panel="#0d4a58",
        dark=True,
    ),
}

THEME_NAMES = list(THEMES.keys())
